### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by flckv** [jongomez/gpthangout#1]
Thanks @jongomez for sharing. I can see you used monorepo setup. I am new to it, so forgive me if I ask a basic question. When you `yarn add a new dependency` in eg. the backendutils.ts, then are you also forced to run`yarn install` in the root directory? What command do you use to avoid updating the dependencies in the other workspace, the packages?

**Comment by jongomez** [comment]
Hey @flckv :wave:

> When you yarn add a new dependency in eg. the backendutils.ts, then are you also forced to runyarn install in the root directory?

We shouldn't have to run `yarn install` in the root directory if I recall correctly :thinking:
If we want to add a dependency to the backendutils.ts file, we should go to the `apps/next` folder, and do `yarn add new-package` - which should do the following:

- Update the `apps/next/package.json` file with the `new-package` dependency. 
- Install `new-package` in the root `node_modules` folder - which, as you say, will make it available to other workspaces.

> What command do you use to avoid updating the dependencies in the other workspace, the packages?

Personally I've never done this. But I believe there are some ways to achieve this - [like using yarn's 'nohoist' workspace feature](
https://classic.yarnpkg.com/blog/2018/02/15/nohoist/), or using the [workspace focus feature perhaps?](https://yarnpkg.com/cli/workspaces/focus) However, I personally would not go down this rabbit hole - it probably won't be easy, and may introduce quite a bit of complexity.

The only reason I'm using workspaces here is because I wanted this project to run on both web and native. However, the native part is not working at the moment. So maybe I should get rid of workspaces altogether... I don't know :man_shrugging:

**Comment by jongomez** [comment]
I got rid of workspaces, hope this clears things up. If not, please feel free to open a new issue, or drop me a message.
